### ISSUE TITLE
Links to Legacy Sessions

### ISSUE THREAD

**Issue by eflamm** [Microsoft-Web/WebCampTrainingKit#14]
This repo is referenced in existing tutorials/HOLs (e.g. [real-time-web-applications-with-signalr]https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/real-time-web-applications-with-signalr , but the files for the lab have been removed. Obviously, there can only be so many sessions in a 1-day web camp, but the legacy code/snippets should still be accessible through links on the source doc. It might be better to have a legacy repo and update the source doc accordingly.

**Comment by csanabria** [comment]
Eric the files for the legacy HOLs are still there, you have to unzip the download and search them.
They've been very usefil for me since I'm working on a real-time application with the SignalR 2 but in Angular 2.

**Comment by jongalloway** [comment]
You can also get the version with the longer SignalR specific lab by grabbing the October 2015 release: https://github.com/Microsoft-Web/WebCampTrainingKit/releases/tag/v2015.10.13b

The Web Camp Training Kit was updated to focus on ASP.NET Core, and SignalR for ASP.NET Core is still being developed.

I'd like to get a new release of the web camp training kit out in the near future updated to the current versions of everything.

**Comment by csanabria** [comment]
Thanks Jon!!!


BTW: I think your presentations and lectures are awesome!! I hope to be lucky enough to get to attend a live one.


____________________________________
Ing. Christian Sanabria J. M.Sc.
Profesional en Tecnologías de Información
csanabria@itcr.ac.cr
Tel. +506 2550-2354, Fax. +506 551-5971
Cel. +506 8818-9979
DATIC - Tecnológico de Costa Rica
________________________________
De: Jon Galloway <notifications@github.com>
Enviado: martes 7 de febrero de 2017 04:53:54 p.m.
Para: Microsoft-Web/WebCampTrainingKit
Cc: Christian Sanabria Jiménez; Comment
Asunto: Re: [Microsoft-Web/WebCampTrainingKit] Links to Legacy Sessions (#14)


Closed #14<https://github.com/Microsoft-Web/WebCampTrainingKit/issues/14>.

**Comment by eflamm** [comment]
I think it's helpful to have the link to previous release in Jon's entry above - hopefully it will help guide anyone looking for the HOL files. 1 caveat - the snippets installer in the HOL folder targets VS2013 (hard-coded); I edited the installCodeSnippets.ps1 PowerShell script before running it to load the snippets into the VS2015 Snippet default folders (My Code Snippets).
[installCodeSnippets.zip](https://github.com/Microsoft-Web/WebCampTrainingKit/files/761701/installCodeSnippets.zip)
