### ISSUE TITLE
Scaffolding item not visible in Visual Studio 2015 after installing ASP.NET 5 RC

### ISSUE THREAD

**Issue by wmeints** [Microsoft-Web/WebCampTrainingKit#4]
I was trying out the demo code for my course next wednesday on ASP.NET 4.6 and 5.
Turns out that the Scaffolding option is gone when you install the RC of ASP.NET 5. 

Don't think I can do anything about that for next wednesday, but if you're still doing workshops based on this trainingkit, don't install ASP.NET 5 RC or show a different demo ;-)

**Comment by jongalloway** [comment]
Scaffolding works, but not in File / New / ASP.NET 5 Empty project. That's being added in future releases, but I'm closing this as it's not a Web Camps issue.
